{
  "config": {
    "abort": {
      "already_configured": "Device is already configured",
      "reauth_sucessful": "Successfully connected"
    },
    "error": {
      "cannot_connect": "Failed to connect",
      "invalid_auth": "Invalid authentication",
      "invalid_boost": "Invalid default boost value",
      "unknown": "Unexpected error"
    },
    "step": {
      "user": {
        "data": {
          "climote_id": "Climote #",
          "password": "Password",
          "username": "Username",
          "interval": "Data Refresh Interval",
          "boost": "Initial Boost Duration",
          "test": "Enable Test Mode"
        }
      },
      "reauth_confirm": {
        "title": "Reauth Required",
        "description": "The Climote integration needs to re-authenticate your account",
        "data": {
          "password": "Password",
          "username": "Username"
        }
      }
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "password": "Password",
          "username": "Username",
          "interval": "Data Refresh Interval",
          "test": "Enable Test Mode"
        }
      }
    }
  }
}
